services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: consilium-backend:dev
    container_name: consilium-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/consilium-db
      SPRING_DATASOURCE_USERNAME: consilium
      SPRING_DATASOURCE_PASSWORD: consilium_password
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - postgres
      - redis
    volumes:
      - ./logs:/app/logs
  postgres:
    image: postgres:15-alpine
    container_name: consilium-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: consilium-db
      POSTGRES_USER: consilium
      POSTGRES_PASSWORD: consilium_password
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    container_name: consilium-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redisdata:/data
volumes:
  pgdata:
  redisdata:


