CREATE TABLE users
(
    user_id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username   VARCHAR(64)                             NOT NULL,
    email      VARCHAR(255)                            NOT NULL,
    password   VARCHAR(255)                            NOT NULL,
    first_name VARCHAR(255)                            NOT NULL,
    last_name  VARCHAR(255),
    created_on TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_on TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (user_id)
);
COMMENT
ON TABLE users IS 'Users table: stores all registered application users';
COMMENT
ON COLUMN users.user_id IS 'Unique identifier for a user, auto-generated by the database';
COMMENT
ON COLUMN users.username IS 'Unique username selected by the user for login and identification';
COMMENT
ON COLUMN users.email IS 'Unique email address for user communication and login';
COMMENT
ON COLUMN users.password IS 'Hashed password for user authentication';
COMMENT
ON COLUMN users.first_name IS 'User''s first name for personalization within the platform';
COMMENT
ON COLUMN users.last_name IS 'User''s last name, optional field for profile completeness';
COMMENT
ON COLUMN users.created_on IS 'Timestamp recording when the user account was initially created';
COMMENT
ON COLUMN users.updated_on IS 'Timestamp recording the last update to the user account';

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

CREATE UNIQUE INDEX idx_users_username ON users (username);